# All model configurations
mlp_001:
  hidden_layer: [7,7,7]
  learning_rate: 0.01
mlp_002:
  hidden_layer: [13,13,13]
  learning_rate: 0.01
mlp_004:
  hidden_layer: [26,26,26]
  learning_rate: 0.005
mlp_008:
  hidden_layer: [36,36,36]
  learning_rate: 0.005
mlp_016:
  hidden_layer: [69,69,69]
  learning_rate: 0.005

moe_001:
  n_experts : 2
  expert_hidden_layer: [4,4,4]
  gate_hidden_layer: [2,2,2]
  learning_rate: 0.01
moe_002:
  n_experts : 2
  expert_hidden_layer: [8,8,8]
  gate_hidden_layer: [4,4,4]
  learning_rate: 0.01
moe_004:
  n_experts : 2
  expert_hidden_layer: [16,16,16]
  gate_hidden_layer: [8,8,8]
  learning_rate: 0.005
moe_008:
  n_experts : 4
  expert_hidden_layer: [16,16,16]
  gate_hidden_layer: [8,8,8]
  learning_rate: 0.005
moe_016:
  n_experts : 4
  expert_hidden_layer: [32,32,32]
  gate_hidden_layer: [16,16,16]
  learning_rate: 0.005